### PR TITLE
feat: automate changelog 

### LINKED ISSUE #15: Manage changelog
I vote for making it automatic by following commit message conventions.

https://www.conventionalcommits.org/en/v1.0.0/
https://github.com/conventional-changelog/standard-version

### PR DESCRIPTION
**Pull request by silentnoodlemaster**
we should still discuss:

-  do we need [commitlint](https://github.com/conventional-changelog/commitlint)
-  do we need to adjust the configuration files
- ???

todo:
- [ ] documentation

closes #15

### CODE REVIEW

**Comment by silentnoodlemaster** [comment]
alternatively [commitizen](https://github.com/commitizen/cz-cli) instead of commitlint

**Comment by taromorimoto** [comment]
How does the automatic versioning work?

**Comment by silentnoodlemaster** [comment]
@taromorimoto 
> How does the automatic versioning work?

this readme will explain it better than i ever could https://github.com/conventional-changelog/standard-version

**Comment by oxyc** [comment]
I think I personally _need_ commitlint/commitizen in the beginning to get used to it :D if we want we can always drop it later.

So we should also update https://github.com/generoi/genero-design-system#publishing-a-new-version

Something like:

```sh
# Create release, generate changelog and bump the version based on commit log
npm run release
# Create a named prerelease version
npm run release -- --prerelease beta
# Manually specifify the version bump
npm run release -- --release-as minor
npm run release -- --release-as 1.1.0


# Push and publish release
git push
git push --tags
npm publish
```

**Comment by oxyc** [comment]
Should we point people to https://www.conventionalcommits.org/en/v1.0.0/ or will the lint error be descriptive enough to lead people there?

**Comment by taromorimoto** [comment]
> If we do, should we point people to https://www.conventionalcommits.org/en/v1.0.0/ or will the lint error be descriptive enough to lead people there?

I would imagine that the lint error should be enough. The readme will anyways talk about using this.

**Comment by taromorimoto** [comment]
@silentnoodlemaster can you add @oxyc's suggestions to readme and merge?

**Pull request merged**
